### ISSUE TITLE
Problems with Fetch

### ISSUE THREAD

**Issue by freitasgst** [freitasgst/weather-cli#1]
ReferenceError: fetch is not defined

Tried using window.fetch, returned ReferenceError: window is not defined.

**Comment by lXSPandora** [comment]
I think you need to use a library to do the fetch for you like i've made at my example
https://github.com/lXSPandora/Node-JS-Darksky-weather-CLI-Application/blob/master/darksky-weather-cli.js#L1

**Comment by jgcmarins** [comment]
you can also use node 8
`fetch` is part of node 8's API \o/

**Comment by freitasgst** [comment]
Using node-fetch worked (though, it's weird, since I'm using node 8.9.4)
